# fly.toml app configuration file generated for defender-wallet-service on 2024-06-23T11:28:44+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'defender-wallet-service'
primary_region = 'waw'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
